# Detectree2: Tree Crown Detection with Adaptive Thresholding
This notebook:
1. Runs Detectree2 inference on all orthomosaics in `input/input_om/`
2. Sweeps confidence thresholds to find the value per OM that yields crown counts closest to the global median
3. Saves the final crowns to `output/input_crowns/OM{n}.gpkg`

In [2]:
# Optional installs (run only if packages are missing)
import sys, subprocess

def ensure(pkg_args):
    if isinstance(pkg_args, str):
        pkg_args = [pkg_args]
    try:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', *pkg_args])
    except Exception as e:
        print(f'Failed to install {pkg_args}: {e}')

# Try imports; if missing, attempt installs.
try:
    import rasterio
except Exception:
    ensure(['rasterio'])

try:
    import geopandas as gpd
except Exception:
    ensure(['geopandas', 'pyproj', 'shapely', 'fiona'])

# Detectron2 stack (may already be present in the environment).
try:
    import detectron2
except Exception:
    # Ensure PyTorch CPU build (safe on macOS) before detectron2
    try:
        import torch
    except Exception:
        ensure(['torch', 'torchvision', 'torchaudio'])
    # Try installing detectron2 from source; may take time.
    ensure(['git+https://github.com/facebookresearch/detectron2.git'])

try:
    import detectree2
except Exception:
    ensure(['git+https://github.com/PatBall1/detectree2.git'])

print('Environment check complete.')

Collecting torch
  Downloading torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl.metadata (25 kB)
Collecting torchvision
  Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio
  Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.4 kB)
Collecting torchvision
  Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.6 kB)
Collecting torchaudio
  Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl.metadata (6.4 kB)
Collecting filelock (from torch)
  Using cached filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torch) (4.15.0)
Collecting sympy (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting filelock (from torch)
  Using cached filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torch) (4.15.0)
Collecting sympy (from torch)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Downloading fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Downloading fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torchvision) (2.2.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torchvision) (12.0.0)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading markupsafe-3.0.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torchvision) (2.2.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from torchvision) (12.0.0)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading markupsafe-3.0.3-cp310-cp310-macosx_10_9_x86_64.whl.metadata (2.7 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl (150.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/150.8 MB ? eta -:--:--Collecting mpmath<1.4,>=1.1.0 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.2.2-cp310-none-macosx_10_9_x86_64.whl (150.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 6.1 MB/s  0:00:24m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 6.1 MB/s  0:00:24m0:00:01
Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.7 MB ? eta -:--:--Downloading torchvision-0.17.2-cp310-cp310-macosx_10_13_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.7 MB/s  0:00:00 eta 0:00:01
Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.7 MB/s  0:00:00 eta 0:00:01
Downloading torchaudio-2.2.2-cp310-cp310-macosx_10_13_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 4.6 MB/s  0:00:00 eta 0:00:01
Using cached filelock-3.20.0-py3-none-any.whl (16 kB)
Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp310-cp310-macosx_10_9_x86_64.whl (11 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 4.6 MB/s  0:00:00 eta 0:00:01
Using cached filelock-3.20.0-py3-none-any.whl (16 kB)
Downloading fsspec-2025.10.0-py3-none-any.whl (200 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp310-cp310-macosx_10_9_x86_64.whl (11 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 9.6 MB/s  0:00:00
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 9.6 MB/s  0:00:00
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision, torchaudio
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/10 [mpmath]Installing collected packages: mpmath, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision, torchaudio
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [torchaudio]0 [torchaudio]]
Successfully installed MarkupSafe-3.0.3 filelock-3.20.0 fsspec-2025.10.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.4.2 sympy-1.14.0 torch-2.2.2 torchaudio-2.2.2 torchvision-0.17.2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [torchaudio]0 [torchaudio]
Successfully installed MarkupSafe-3.0.3 filelock-3.20.0 fsspec-2025.10.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.4.2 sympy-1.14.0 torch-2.2.2 torchaudio-2.2.2 torchvision-0.17.2
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/pip-req-build-7kb1cc7z
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /private/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/pip-req-build-7kb1cc7z

  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /private/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/pip-req-build-7kb1cc7z

  Resolved https://github.com/facebookresearch/detectron2.git to commit a9c0821a12ad353fb2a96f019515990d5460c5ac
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Pillow>=7.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (12.0.0)
Requirement already satisfied: matplotlib in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (3.10.7)
Requirement already satisfied: pycocotools>=2.0.2 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (2.0.10)
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: Pillow>=7.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (12.0.0)
Requirement already satisfied: matplotlib in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (3.10.7)
Requirement already satisfied: pycocotools>=2.0.2 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (2.0.10)

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/termcolor/

Collecting termcolor>=1.1 (from detectron2==0.6)
  Downloading termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
Collecting yacs>=0.1.8 (from detectron2==0.6)
  Using cached yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Collecting tabulate (from detectron2==0.6)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting cloudpickle (from detectron2==0.6)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tqdm>4.29.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (4.67.1)
Collecting yacs>=0.1.8 (from detectron2==0.6)
  Using cached yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)
Collecting tabulate (from detectron2==0.6)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting cloudpickle (from detectron2==0.6)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tqdm>4.29.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (4.67.1)
Collecting tensorboard (from detectron2==0.6)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting tensorboard (from detectron2==0.6)
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting fvcore<0.1.6,>=0.1.5 (from detectron2==0.6)
  Using cached fvcore-0.1.5.post20221221-py3-none-any.whl
Collecting fvcore<0.1.6,>=0.1.5 (from detectron2==0.6)
  Using cached fvcore-0.1.5.post20221221-py3-none-any.whl
Collecting iopath<0.1.10,>=0.1.7 (from detectron2==0.6)
  Using cached iopath-0.1.9-py3-none-any.whl.metadata (370 bytes)
Collecting omegaconf<2.4,>=2.1 (from detectron2==0.6)
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting hydra-core>=1.1 (from detectron2==0.6)
  Using cached hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting iopath<0.1.10,>=0.1.7 (from detectron2==0.6)
  Using cached iopath-0.1.9-py3-none-any.whl.metadata (370 bytes)
Collecting omegaconf<2.4,>=2.1 (from detectron2==0.6)
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting hydra-core>=1.1 (from detectron2==0.6)
  Using cached hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting black (from detectron2==0.6)
  Downloading black-25.9.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (83 kB)
Requirement already satisfied: packaging in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (25.0)
Requirement already satisfied: numpy in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (2.2.6)
Requirement already satisfied: pyyaml>=5.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0.3)
Collecting portalocker (from iopath<0.1.10,>=0.1.7->detectron2==0.6)
  Using cached portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<2.4,>=2.1->detectron2==0.6)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting black (from detectron2==0.6)
  Downloading black-25.9.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (83 kB)
Requirement already satisfied: packaging in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from detectron2==0.6) (25.0)
Requirement already satisfied: numpy in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (2.2.6)
Requirement already satisfied: pyyaml>=5.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0.3)
Collecting portalocker (from iopath<0.1.10,>=0.1.7->detectron2==0.6)
  Using cached portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<2.4,>=2.1->detectron2==0.6)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Requirement already satisfied: click>=8.0.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (8.3.0)
Collecting mypy-extensions>=0.4.3 (from black->detectron2==0.6)
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=0.9.0 (from black->detectron2==0.6)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs>=2 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (4.5.0)
Collecting pytokens>=0.1.10 (from black->detectron2==0.6)
  Downloading pytokens-0.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: click>=8.0.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (8.3.0)
Collecting mypy-extensions>=0.4.3 (from black->detectron2==0.6)
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=0.9.0 (from black->detectron2==0.6)
  Using cached pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs>=2 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (4.5.0)
Collecting pytokens>=0.1.10 (from black->detectron2==0.6)
  Downloading pytokens-0.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting tomli>=1.1.0 (from black->detectron2==0.6)
  Downloading tomli-2.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->detectron2==0.6) (1.17.0)
Collecting tomli>=1.1.0 (from black->detectron2==0.6)
  Downloading tomli-2.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from black->detectron2==0.6) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from matplotlib->detectron2==0.6) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->detectron2==0.6) (1.17.0)
Collecting absl-py>=0.4 (from tensorboard->detectron2==0.6)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting absl-py>=0.4 (from tensorboard->detectron2==0.6)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard->detectron2==0.6)
  Downloading grpcio-1.76.0-cp310-cp310-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting markdown>=2.6.8 (from tensorboard->detectron2==0.6)
  Using cached markdown-3.9-py3-none-any.whl.metadata (5.1 kB)
Collecting grpcio>=1.48.2 (from tensorboard->detectron2==0.6)
  Downloading grpcio-1.76.0-cp310-cp310-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting markdown>=2.6.8 (from tensorboard->detectron2==0.6)
  Using cached markdown-3.9-py3-none-any.whl.metadata (5.1 kB)
Collecting protobuf!=4.24.0,>=3.19.6 (from tensorboard->detectron2==0.6)
  Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: setuptools>=41.0.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from tensorboard->detectron2==0.6) (78.1.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard->detectron2==0.6)
  Using cached tensorboard_data_server-0.7.2-py3-none-macosx_10_9_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard->detectron2==0.6)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard->detectron2==0.6) (3.0.3)
Using cached iopath-0.1.9-py3-none-any.whl (27 kB)
Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Downloading termcolor-3.2.0-py3-none-any.whl (7.7 kB)
Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Collecting protobuf!=4.24.0,>=3.19.6 (from tensorboard->detectron2==0.6)
  Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: setuptools>=41.0.0 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from tensorboard->detectron2==0.6) (78.1.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard->detectron2==0.6)
  Using cached tensorboard_data_server-0.7.2-py3-none-macosx_10_9_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard->detectron2==0.6)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard->detectron2==0.6) (3.0.3)
Using cached iopath-0.1.9-py3-none-any.whl (27 kB)
Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Using cached hydra_core-1.3.2-py3-none-any.whl (154 kB)
Downloading termcolor-3.2.0-py3-none-any.whl (7.7 kB)
Using cached yacs-0.1.8-py3-none-any.whl (14 kB)
Downloading black-25.9.0-cp310-cp310-macosx_10_9_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/1.7 MB ? eta -:--:--Downloading black-25.9.0-cp310-cp310-macosx_10_9_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.2 MB/s  0:00:00 eta 0:00:01
Using cached mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Downloading pytokens-0.2.0-py3-none-any.whl (12 kB)
Downloading tomli-2.3.0-py3-none-any.whl (14 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached portalocker-3.2.0-py3-none-any.whl (22 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-macosx_10_9_x86_64.whl (4.8 MB)
Using cached absl_py-2.3.1-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.2 MB/s  0:00:00
Using cached mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Using cached pathspec-0.12.1-py3-none-any.whl (31 kB)
Downloading pytokens-0.2.0-py3-none-any.whl (12 kB)
Downloading tomli-2.3.0-py3-none-any.whl (14 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached portalocker-3.2.0-py3-none-any.whl (22 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-macosx_10_9_x86_64.whl (4.8 MB)
Using cached absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading grpcio-1.76.0-cp310-cp310-macosx_11_0_universal2.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/11.8 MB ? eta -:--:--Downloading grpcio-1.76.0-cp310-cp310-macosx_11_0_universal2.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 5.0 MB/s  0:00:02 eta 0:00:01
Using cached markdown-3.9-py3-none-any.whl (107 kB)
Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 5.0 MB/s  0:00:02 eta 0:00:01
Using cached markdown-3.9-py3-none-any.whl (107 kB)
Downloading protobuf-6.33.0-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Using cached werkzeug-3.1.3-py3-none-any.whl (224 kB)
Building wheels for collected packages: detectron2
  Building wheel for detectron2 (setup.py): started
Using cached werkzeug-3.1.3-py3-none-any.whl (224 kB)
Building wheels for collected packages: detectron2
  Building wheel for detectron2 (setup.py): started

  DEPRECATION: Building 'detectron2' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'detectron2'. Discussion can be found at https://github.com/pypa/pip/issues/6334

  Building wheel for detectron2 (setup.py): still running...
  Building wheel for detectron2 (setup.py): finished with status 'done'
  Created wheel for detectron2: filename=detectron2-0.6-cp310-cp310-macosx_10_15_x86_64.whl size=870145 sha256=ff2b585654ca20ae0c91baef7f22e3a9bca15dd5c687c62e95854f7f587440e5
  Stored in directory: /private/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/pip-ephem-wheel-cache-prdwp9ut/wheels/47/e5/15/94c80df2ba85500c5d76599cc307c0a7079d0e221bb6fc4375
Successfully built detectron2
  Building wheel for detectron2 (setup.py): finished with status 'done'
  Created wheel for detectron2: filename=detectron2-0.6-cp310-cp310-macosx_10_15_x86_64.whl size=870145 sha256=ff2b585654ca20ae0c91baef7f22e3a9bca15dd5c687c62e95854f7f587440e5
  Stored in directory: /private/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/pip-ephem-wheel-cache-prdwp9ut/wheels/47/e5/15/94c80df2ba85500c5d76599cc307c0a7079d0e221bb6fc4375
Successfully built detectron2
Installing collected packages: antlr4-python3-runtime, yacs, werkzeug, tomli, termcolor, tensorboard-data-server, tabulate, pytokens, protobuf, portalocker, pathspec, omegaconf, mypy-extensions, markdown, grpcio, cloudpickle, absl-py, tensorboard, iopath, hydra-core, black, fvcore, detectron2
   ━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/23 [werkzeug]Installing collected packages: antlr4-python3-runtime, yacs, werkzeug, tomli, termcolor, tensorboard-data-server, tabulate, pytokens, protobuf, portalocker, pathspec, omegaconf, mypy-extensions, markdown, grpcio, cloudpickle, absl-py, tensorboard, iopath, hydra-core, black, fvcore, detectron2
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23/23 [detectron2]3 [detectron2]]data-server]
Successfully installed absl-py-2.3.1 antlr4-python3-runtime-4.9.3 black-25.9.0 cloudpickle-3.1.2 detectron2-0.6 fvcore-0.1.5.post20221221 grpcio-1.76.0 hydra-core-1.3.2 iopath-0.1.9 markdown-3.9 mypy-extensions-1.1.0 omegaconf-2.3.0 pathspec-0.12.1 portalocker-3.2.0 protobuf-6.33.0 pytokens-0.2.0 tabulate-0.9.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 termcolor-3.2.0 tomli-2.3.0 werkzeug-3.1.3 yacs-0.1.8
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23/23 [detectron2]3 [detectron2]
Successfully installed absl-py-2.3.1 antlr4-python3-runtime-4.9.3 black-25.9.0 cloudpickle-3.1.2 detectron2-0.6 fvcore-0.1.5.post20221221 grpcio-1.76.0 hydra-core-1.3.2 iopath-0.1.9 markdown-3.9 mypy-extensions-1.1.0 omegaconf-2.3.0 pathspec-0.12.1 portalocker-3.2.0 protobuf-6.33.0 pytokens-0.2.0 tabulate-0.9.0 tensorboard-2.20.0 tensorboard-data-server-0.7.2 termcolor-3.2.0 tomli-2.3.0 werkzeug-3.1.3 yacs-0.1.8
Environment check complete.
Environment check complete.

In [3]:
# Core detection utilities
import os
import warnings
import rasterio
import geopandas as gpd

from detectree2.preprocessing.tiling import tile_data
from detectree2.models.train import setup_cfg
from detectree2.models.predict import predict_on_data
from detectree2.models.outputs import project_to_geojson, stitch_crowns, clean_crowns
from detectron2.engine import DefaultPredictor

def tile_orthomosaic(img_path, tiles_path, buffer=20, tile_width=45, tile_height=45, dtype_bool=True):
    os.makedirs(tiles_path, exist_ok=True)
    tile_data(img_path, tiles_path, buffer, tile_width, tile_height, dtype_bool=dtype_bool)

def setup_detection_config(trained_model_path, device='cpu'):
    cfg = setup_cfg(update_model=trained_model_path)
    try:
        cfg.MODEL.DEVICE = device
    except Exception:
        pass
    return cfg

def predict_tree_crowns(tiles_path, cfg):
    predictor = DefaultPredictor(cfg)
    predict_on_data(directory=tiles_path, predictor=predictor)

def reproject_predictions(tiles_path):
    predictions_folder = os.path.join(tiles_path, 'predictions/')
    geo_predictions_folder = os.path.join(tiles_path, 'predictions_geo/')
    project_to_geojson(tiles_path, predictions_folder, geo_predictions_folder)
    return geo_predictions_folder

def tree_crown_detection_pipeline(img_path, tiles_path, trained_model_path,
                                   buffer=20, tile_width=45, tile_height=45, dtype_bool=True,
                                   device='cpu'):
    # Tile
    tile_orthomosaic(img_path, tiles_path, buffer, tile_width, tile_height, dtype_bool)
    # Config
    cfg = setup_detection_config(trained_model_path, device=device)
    # Predict
    predict_tree_crowns(tiles_path, cfg)
    # Reproject
    geo_predictions_folder = reproject_predictions(tiles_path)
    return geo_predictions_folder

/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 614, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_shell
    await result
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 366, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 827, in execute_request
    reply_content = await reply_content
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 458, in do_execute
    res = shell.run_cell(
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/ipykernel_33462/2998008189.py", line 8, in <module>
    from detectree2.models.train import setup_cfg
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectree2/models/train.py", line 20, in <module>
    import detectron2.data.transforms as T  # noqa:N812
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectron2/__init__.py", line 3, in <module>
    from .utils.env import setup_environment
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectron2/utils/env.py", line 10, in <module>
    import torch
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 758, in start
    self.io_loop.start()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/utils.py", line 71, in preserve_context
    return await f(*args, **kwargs)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 614, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_shell
    await result
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 366, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 827, in execute_request
    reply_content = await reply_content
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 458, in do_execute
    res = shell.run_cell(
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 663, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3077, in run_cell
    result = self._run_cell(
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3132, in _run_cell
    result = runner(coro)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3336, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3519, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3579, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/ipykernel_33462/2998008189.py", line 8, in <module>
    from detectree2.models.train import setup_cfg
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectree2/models/train.py", line 20, in <module>
    import detectron2.data.transforms as T  # noqa:N812
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectron2/__init__.py", line 3, in <module>
    from .utils.env import setup_environment
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/detectron2/utils/env.py", line 10, in <module>
    import torch
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/hbot07/anaconda3/envs/detectree/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

In [5]:
# Step 1: Run detection for all orthomosaics
import os
import glob
import re

project_root = '/Users/hbot07/VS Code/Drone-Phenology-Monitoring'
input_dir = os.path.join(project_root, 'input')
om_dir = os.path.join(input_dir, 'input_om')
tiles_dir = os.path.join(input_dir, 'tiles')
model_path = os.path.join(input_dir, 'detectree_models', '250312_flexi.pth')

# Collect orthomosaics
om_paths = sorted(glob.glob(os.path.join(om_dir, '*.tif')))
if not om_paths:
    raise FileNotFoundError(f"No orthomosaics found in {om_dir}")

print(f"Found {len(om_paths)} orthomosaics. Running detection...")

# Run detection pipeline (inference only)
params = dict(buffer=20, tile_width=45, tile_height=45, dtype_bool=True, device='cpu')

for om_path in om_paths:
    stem = os.path.splitext(os.path.basename(om_path))[0]
    tiles_path = os.path.join(tiles_dir, stem)
    geo_predictions_folder = os.path.join(tiles_path, 'predictions_geo')
    
    print(f"\n=== Processing {stem} ===")
    print("Orthomosaic:", om_path)
    print("Tiles dir  :", tiles_path)
    
    # Skip if predictions already exist
    if os.path.isdir(geo_predictions_folder) and glob.glob(os.path.join(geo_predictions_folder, '*.geojson')):
        print(f"Predictions already exist, skipping detection: {geo_predictions_folder}")
        continue
    
    # Run detection (returns path to predictions_geo/)
    geo_predictions_folder = tree_crown_detection_pipeline(
        img_path=om_path,
        tiles_path=tiles_path,
        trained_model_path=model_path,
        **params
    )
    print(f"Predictions saved to: {geo_predictions_folder}")

print("\nDetection complete for all orthomosaics.")

Found 5 orthomosaics. Running detection...

=== Processing sit_om1 ===
Orthomosaic: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/input_om/sit_om1.tif
Tiles dir  : /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om1
Predictions already exist, skipping detection: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om1/predictions_geo

=== Processing sit_om2 ===
Orthomosaic: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/input_om/sit_om2.tif
Tiles dir  : /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om2
Predictions already exist, skipping detection: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om2/predictions_geo

=== Processing sit_om3 ===
Orthomosaic: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/input_om/sit_om3.tif
Tiles dir  : /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om3
Predictions already exist, skipping detection: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om3/predictions_geo

=== Processing sit_om4 ===
Orthomosaic: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/input_om/sit_om4.tif
Tiles dir  : /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om4
Predictions already exist, skipping detection: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om4/predictions_geo

=== Processing sit_om5 ===
Orthomosaic: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/input_om/sit_om5.tif
Tiles dir  : /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om5
Predictions already exist, skipping detection: /Users/hbot07/VS Code/Drone-Phenology-Monitoring/input/tiles/sit_om5/predictions_geo

Detection complete for all orthomosaics.

In [6]:
# Step 2: Confidence sweep and adaptive threshold selection
import numpy as np
import pandas as pd
from detectree2.models.outputs import stitch_crowns, clean_crowns

# Fix PROJ data directory issue
import pyproj
try:
    pyproj_datadir = pyproj.datadir.get_data_dir()
except Exception:
    import subprocess
    result = subprocess.run(['conda', 'info', '--base'], capture_output=True, text=True)
    conda_base = result.stdout.strip()
    proj_data = os.path.join(conda_base, 'share', 'proj')
    if os.path.exists(proj_data):
        pyproj.datadir.set_data_dir(proj_data)
        print(f"Set PROJ_DATA to: {proj_data}")
    else:
        print("Warning: PROJ data directory not found, proceeding anyway...")

# Fixed parameters
fixed_iou = 0.7
fixed_simplify = 0.3
conf_list = [0.35, 0.40, 0.45, 0.50, 0.55, 0.60]

# Output directory
output_crowns_dir = os.path.join(project_root, 'output', 'input_crowns')
os.makedirs(output_crowns_dir, exist_ok=True)

# Naming function: sit_om{n}.tif -> OM{n}.gpkg
om_num_pat = re.compile(r"sit_om(\d+)", re.IGNORECASE)

def out_name_for(stem: str) -> str:
    m = om_num_pat.search(stem)
    if m:
        return f"OM{int(m.group(1))}.gpkg"
    return f"{stem}_crowns.gpkg"

def load_stitched_for(stem: str):
    geo_folder = os.path.join(tiles_dir, stem, 'predictions_geo')
    if not (os.path.isdir(geo_folder) and glob.glob(os.path.join(geo_folder, '*.geojson'))):
        return None
    gdf = stitch_crowns(geo_folder, 1)
    gdf = gdf[gdf.is_valid]
    return gdf

def compute_count_for_conf(base: gpd.GeoDataFrame, conf: float) -> int:
    g = base.copy()
    if fixed_simplify and fixed_simplify > 0:
        g = g.set_geometry(g.geometry.simplify(fixed_simplify))
    g = clean_crowns(g, fixed_iou, conf)
    g = g[g.is_valid]
    return int(len(g))

# Collect orthomosaic stems
stems = [os.path.splitext(os.path.basename(p))[0] for p in om_paths]

print("Running confidence sweep...")
rows = []
bases = {}

for stem in stems:
    base = load_stitched_for(stem)
    if base is None:
        print(f"Skipping {stem}: predictions not found")
        continue
    bases[stem] = base
    for conf in conf_list:
        count = compute_count_for_conf(base, conf)
        rows.append({'orthomosaic': stem, 'confidence': conf, 'count': count})

if not rows:
    raise RuntimeError('No stitched predictions found. Run detection first.')

sweep_df = pd.DataFrame(rows)
target_count = int(np.median(sweep_df['count']))
print(f"Global median count across all OM×conf: {target_count}")

# Select confidence per OM closest to target
def choose_conf_for_counts(df: pd.DataFrame, target: int) -> pd.Series:
    diffs = (df['count'] - target).abs()
    min_diff = diffs.min()
    candidates = df.loc[diffs == min_diff]
    chosen = candidates.sort_values('confidence', ascending=False).iloc[0]
    return pd.Series({'chosen_conf': float(chosen['confidence']), 'chosen_count': int(chosen['count'])})

chosen = (sweep_df.groupby('orthomosaic')
          .apply(lambda d: choose_conf_for_counts(d.sort_values('confidence'), target_count))
          .reset_index())

print("\nChosen thresholds per orthomosaic:")
display(chosen)

# Save chosen crowns
print("\nSaving crowns with chosen thresholds...")
export_rows = []

for _, r in chosen.iterrows():
    stem = r['orthomosaic']
    conf = float(r['chosen_conf'])
    base = bases.get(stem)
    if base is None:
        continue
    
    # Apply chosen threshold
    g = base.copy()
    if fixed_simplify and fixed_simplify > 0:
        g = g.set_geometry(g.geometry.simplify(fixed_simplify))
    g = clean_crowns(g, fixed_iou, conf)
    g = g[g.is_valid]
    
    # Save
    out_file = os.path.join(output_crowns_dir, out_name_for(stem))
    try:
        g.to_file(out_file, driver='GPKG')
        export_rows.append({
            'orthomosaic': stem, 
            'confidence': conf, 
            'count': int(len(g)), 
            'output': out_file
        })
        print(f"  {stem}: conf={conf:.2f}, count={len(g)} → {out_file}")
    except Exception as e:
        print(f"  Failed to save {stem}: {e}")

print(f"\nAll crowns saved to {output_crowns_dir}")

# Summary
summary = pd.DataFrame(export_rows)
display(summary)

Running confidence sweep...
clearn_crowns: Performing spatial join...
clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 498/498 [00:00<00:00, 4055.41it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 350/350 [00:00<00:00, 5887.59it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 280/280 [00:00<00:00, 5444.72it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 242/242 [00:00<00:00, 5149.49it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 210/210 [00:00<00:00, 4781.65it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 186/186 [00:00<00:00, 6085.86it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 536/536 [00:00<00:00, 4228.73it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 436/436 [00:00<00:00, 4707.57it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 362/362 [00:00<00:00, 5203.55it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 308/308 [00:00<00:00, 3931.12it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 254/254 [00:00<00:00, 6577.76it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 220/220 [00:00<00:00, 5387.67it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 342/342 [00:00<00:00, 5086.87it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 260/260 [00:00<00:00, 5639.81it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 184/184 [00:00<00:00, 5694.12it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 132/132 [00:00<00:00, 5924.35it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 112/112 [00:00<00:00, 5777.07it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 102/102 [00:00<00:00, 4791.66it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 218/218 [00:00<00:00, 6217.38it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 156/156 [00:00<00:00, 5657.88it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 116/116 [00:00<00:00, 6813.13it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 92/92 [00:00<00:00, 5872.23it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 78/78 [00:00<00:00, 6475.13it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 66/66 [00:00<00:00, 6250.54it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 320/320 [00:00<00:00, 5092.70it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 256/256 [00:00<00:00, 4780.60it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 202/202 [00:00<00:00, 6337.04it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 178/178 [00:00<00:00, 6251.77it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 158/158 [00:00<00:00, 6061.02it/s]

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 110/110 [00:00<00:00, 6441.78it/s]

Global median count across all OM×conf: 82

Chosen thresholds per orthomosaic:

/var/folders/cx/8v11zwh97cxgdgt_ph13_56r0000gn/T/ipykernel_33462/2260526651.py:88: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda d: choose_conf_for_counts(d.sort_values('confidence'), target_count))

  orthomosaic  chosen_conf  chosen_count
0     sit_om1         0.55          82.0
1     sit_om2         0.50          85.0
2     sit_om3         0.45          78.0
3     sit_om4         0.40          80.0
4     sit_om5         0.50          83.0

Saving crowns with chosen thresholds...
clearn_crowns: Performing spatial join...
clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 210/210 [00:00<00:00, 7182.73it/s]

  sit_om1: conf=0.55, count=82 → /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns/OM1.gpkg

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 308/308 [00:00<00:00, 6333.63it/s]

  sit_om2: conf=0.50, count=85 → /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns/OM2.gpkg

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 184/184 [00:00<00:00, 6150.35it/s]

  sit_om3: conf=0.45, count=78 → /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns/OM3.gpkg

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 156/156 [00:00<00:00, 6122.21it/s]

  sit_om4: conf=0.40, count=80 → /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns/OM4.gpkg

clearn_crowns: Performing spatial join...

clean_crowns: Processing candidate pairs: 100%|██████████| 178/178 [00:00<00:00, 5299.18it/s]

  sit_om5: conf=0.50, count=83 → /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns/OM5.gpkg

All crowns saved to /Users/hbot07/VS Code/Drone-Phenology-Monitoring/output/input_crowns

,orthomosaic,confidence,count,output
0,sit_om1,0.55,82,/Users/hbot07/VS Code/Drone-Phenology-Monitori...
1,sit_om2,0.50,85,/Users/hbot07/VS Code/Drone-Phenology-Monitori...
2,sit_om3,0.45,78,/Users/hbot07/VS Code/Drone-Phenology-Monitori...
3,sit_om4,0.40,80,/Users/hbot07/VS Code/Drone-Phenology-Monitori...
4,sit_om5,0.50,83,/Users/hbot07/VS Code/Drone-Phenology-Monitori...